<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist
  PUBLIC '-//Apple//DTD PLIST 1.0//EN'
  'http://www.apple.com/DTDs/PropertyList-1.0.dtd'>
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>cos</string>
		</array>
		<key>foldingStartMarker</key>
		<string>scrp</string>
		<key>foldingStopMarker</key>
		<string>endm</string>
		<key>name</key>
		<string>CAOS</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>match</key>
				<string>\b([1-9]+[0-9]*|0)</string>
				<key>name</key>
				<string>constant.numeric.integer.decimal</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(&lt;|&lt;\=|\=|&gt;|&gt;\=|&lt;&gt;|eq|ne|gt|ge|lt|le)\b</string>
				<key>name</key>
				<string>keyword.operator.comparison.python</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Agent Stuff</string>
				<key>match</key>
				<string>\b(abba|alph|anim|anms|attr|attr|base|base|bhvr|bhvr|call|carr|cata|cati|cato|catx|clac|clik|core|dcor|disq|drop|dsee|enum|esee|etch|fltx|flty|fmly|frat|from|gait|gall|gall|gnus|hand|hand|held|hght|iitt|imsk|kill|mesg writ|mesg wrt+|mira|mira|mows|mthx|mthy|ncls|new: simp|next|nohh|null|over|ownr|paus|paus|pcls|plne|plne|pntr|posb|pose|pose|posl|posr|post|posx|posy|puhl|puhl|pupt|pupt|rnge|rnge|rtar|seee|show|spcs|star|targ|tcor|tick|tick|tino|tint|tint|totl|touc|tran|ttar|twin|ucln|visi|wdth|wild|_it_)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Brain Stuff</string>
				<key>match</key>
				<string>\b(adin|brn: dmpb|brn: dmpd|brn: dmpl|brn: dmpn|brn: dmpt|brn: setd|brn: setl|brn: setn|brn: sett|doin)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Camera Stuff</string>
				<key>match</key>
				<string>\b(bkgd|bkgd|brmi|cmra|cmrp|cmrt|cmrx|cmry|frsh|line|loft|meta|meta|scam|snap|snax|trck|trck|wdow|wdow|wndb|wndh|wndl|wndr|wndt|wndw|zoom)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>CD Player Stuff</string>
				<key>match</key>
				<string>\b(_cd_ ejct|_cd_ frqh|_cd_ frql|_cd_ frqm|_cd_ init|_cd_ paws|_cd_ play|_cd_ shut|_cd_ stop)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Compunds Stuff</string>
				<key>match</key>
				<string>\b(fcus|frmt|grpl|grpv|new: comp|npgs|page|page|part|part|pat: butt|pat: cmra|pat: dull|pat: fixd|pat: grph|pat: kill|pat: move|pat: text|pnxt|ptxt|ptxt)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Creatures Stuff</string>
				<key>match</key>
				<string>\b(ages|appr|aslp|aslp|attn|body|body|boot|born|bvar|byit|cage|calg|calg|chem|chem|crea|dead|dead|decn|dftx|dfty|dirn|dirn|done|drea|drea|driv|driv|drv!|expr|face|face|face|forf|hair|hhld|injr|ins#|like|limb|loci|loci|ltcy|mate|mind|mind|motr|motr|mvft|new: crag|new: crea|newc|norn|norn|nude|ordr shou|ordr sign|ordr tact|ordr writ|orgf|orgi|orgn|plmd|plmu|sayn|seen|soul|soul|spnl|step|stim shou|stim sign|stim tact|stim writ|sway shou|sway sign|sway tact|sway writ|tage|touc|uftx|ufty|uncs|uncs|urge shou|urge sign|urge tact|urge writ|vocb|walk|wear|zomb|zomb)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Debug Stuff</string>
				<key>match</key>
				<string>\b(agnt|apro|bang|code|codf|codg|codp|cods|dbg#|dbg: asrt|dbg: cpro|dbg: flsh|dbg: html|dbg: outs|dbg: outv|dbg: paws|dbg: play|dbg: poll|dbg: prof|dbg: tack|dbg: tock|dbg: wtik|dbga|heap|help|mann|memx|paws|tack|unid)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Files Stuff</string>
				<key>match</key>
				<string>\b(file glob|file iclo|file iope|file jdel|file oclo|file oflu|file oope|fvwm|innf|inni|innl|inok|outs|outv|outx|webb)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Flow Stuff</string>
				<key>match</key>
				<string>\b(scrp|endm|doif|elif|else|endi|ever|goto|gsub|loop|repe|reps|retn|subr|untl|rscr)\b</string>
				<key>name</key>
				<string>keyword.control</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Genetics Stuff</string>
				<key>match</key>
				<string>\b(gene clon|gene cros|gene kill|gene load|gene move|gtos|mtoa|mtoc)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>History Stuff</string>
				<key>match</key>
				<string>\b(hist cage|hist coun|hist cros|hist evnt|hist find|hist finr|hist foto|hist foto|hist gend|hist gnus|hist mon1|hist mon2|hist mute|hist name|hist name|hist netu|hist next|hist prev|hist rtim|hist tage|hist type|hist utxt|hist utxt|hist vari|hist wipe|hist wnam|hist wtik|hist wuid|hist wvet|ooww)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Input Stuff</string>
				<key>match</key>
				<string>\b(clac|clik|hotp|hots|imsk|keyd|mopx|mopy|mous|movx|movy|pure|pure|tran)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Map Stuff</string>
				<key>match</key>
				<string>\b(addb|addm|addr|altr|bkds|cacl|calc|delm|delr|dmap|doca|door|door|down|emid|emit|erid|gmap|grap|grid|hirp|left|link|link|lorp|mapd|maph|mapk|mapw|mloc|perm|perm|prop|prop|rate|rate|rght|rloc|room|rtyp|rtyp|torx|tory|_up_)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Motion Stuff</string>
				<key>match</key>
				<string>\b(accg|accg|admp|admp|aero|aero|angl|avel|avel|elas|elas|fall|fdmp|fdmp|flto|frel|fric|fric|fvel|fvel|movs|mvby|mvsf|mvto|obst|relx|rely|rotn|sdmp|sdmp|spin|spin|svel|svel|tmvb|tmvf|tmvt|varc|varc|vecx|vecy|velo|velx|vely|wall)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Net Commands Stuff</string>
				<key>match</key>
				<string>\b(net: erra|net: expo|net: from|net: head|net: hear|net: host|net: line|net: line|net: pass|net: pass|net: rawe|net: ruso|net: stat|net: ulin|net: unik|net: user|net: what|net: whod|net: whof|net: whon|net: whoz|net: writ)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Ports Stuff</string>
				<key>match</key>
				<string>\b(econ|prt: bang|prt: frma|prt: from|prt: inew|prt: itot|prt: izap|prt: join|prt: krak|prt: name|prt: onew|prt: otot|prt: ozap|prt: send)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Ressources Stuff</string>
				<key>match</key>
				<string>\b(net: make|pray agti|pray agts|pray back|pray coun|pray deps|pray expo|pray file|pray fore|pray garb|pray impo|pray injt|pray kill|pray make|pray next|pray prev|pray refr|pray test)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Script Stuff</string>
				<key>match</key>
				<string>\b(caos|gids fmly|gids gnus|gids root|gids spcs|inst|ject|lock|scrx|slow|sorc|sorq|stop|stpt|unlk|wait)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Sounds Stuff</string>
				<key>match</key>
				<string>\b(fade|mclr|midi|mmsc|mmsc|mute|rclr|rmsc|rmsc|sezz|sndc|snde|sndl|sndq|stpc|strk|voic|vois|vois|volm|volm)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Time Stuff</string>
				<key>match</key>
				<string>\b(buzz|buzz|date|dayt|etik|hist date|hist sean|hist time|hist year|mont|msec|pace|race|rtif|rtim|scol|sean|time|wolf|wpau|wpau|wtik|year)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Variables Stuff</string>
				<key>match</key>
				<string>\b(absv|acos|adds|addv|andv|asin|atan|avar|char|char|cos_|dele|delg|deln|divv|eame|eamn|ftoi|game|gamn|gnam|itof|lowa|mame|modu|modv|mulv|mvxx|name|namn|negv|notv|orrv|ovxx|rand|read|reaf|rean|reaq|seta|sets|setv|sins|sin_|sqrt|stof|stoi|strl|subs|subv|tan_|targ|type|ufos|uppa|vaxx|vmjr|vmnr|vtos|_p1_|_p2_)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Vehicles Stuff</string>
				<key>match</key>
				<string>\b(cabb|cabl|cabn|cabp|cabp|cabr|cabt|cabv|cabv|cabw|dpas|epas|gpas|new: vhcl|rpas|spas)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>World Stuff</string>
				<key>match</key>
				<string>\b(delw|load|nwld|pswd|pswd|quit|rgam|save|tntw|wnam|wnti|wrld|wrld|wtnt|wuid)\b</string>
				<key>name</key>
				<string>support.function</string>
			</dict>
			<dict>
				<key>begin</key>
				<string>&quot;</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end</string>
					</dict>
				</dict>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin</string>
					</dict>
				</dict>
				<key>name</key>
				<string>string.quoted.double.dosbatch</string>
				<key>end</key>
				<string>&quot;</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.comment.sql</string>
					</dict>
				</dict>
				<key>match</key>
				<string>(\*).*$\n?</string>
				<key>name</key>
				<string>comment.line.number-sign.sql</string>
			</dict>
		</array>
		<key>scopeName</key>
		<string>source.cos</string>
		<key>uuid</key>
		<string>1BA75B32-707C-11D9-A928-000D98989AF6</string>
	</dict>
</plist>